name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: [ "master" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@v0.0.7
      with:
        project_name: 'project-ncl/causeway'
      secrets: inherit
